#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct.
docker build \
  --build-arg REVISION=`git rev-parse --short HEAD` \
  --build-arg CREATED=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  -t $IMAGE_NAME .
